name: algo_viz
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  another_flutter_splash_screen: ^1.2.0
  bloc: 8.1.3

  cupertino_icons: ^1.0.6


  flutter:
    sdk: flutter

  flutter_bloc: 8.1.4

  fpdart: 1.1.0

  freezed_annotation: 2.4.1

  get_it: 7.6.7

  injectable: 2.3.2

  intl: 0.19.0

  json_annotation: 4.8.1

  lottie: ^3.1.0
  pin_code_fields: 8.0.1

  recase: 4.1.0

  uuid: 4.3.3

dev_dependencies:
  build_runner: 2.4.8

  flutter_lints: ^3.0.0

  flutter_test:
    sdk: flutter

  freezed: 2.4.7

  injectable_generator: 2.4.1

  json_serializable: 6.7.1

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/lottie/
    - assets/images/